In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('pokemon_data.csv')

In [3]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [6]:
print(df['Legendary'][90:57:-1])

90    False
89    False
88    False
87    False
86    False
85    False
84    False
83    False
82    False
81    False
80    False
79    False
78    False
77    False
76    False
75    False
74    False
73    False
72    False
71    False
70    False
69    False
68    False
67    False
66    False
65    False
64    False
63    False
62    False
61    False
60    False
59    False
58    False
Name: Legendary, dtype: bool

In [24]:
df.iloc[8]

#                                     6
Name          CharizardMega Charizard Y
Type 1                             Fire
Type 2                           Flying
HP                                   78
Attack                              104
Defense                              78
Sp. Atk                             159
Sp. Def                             115
Speed                               100
Generation                            1
Legendary                         False
Name: 8, dtype: object

In [9]:
print(df.iloc[0:9])

   #                       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1                  Bulbasaur  Grass  Poison  45      49       49       65
1  2                    Ivysaur  Grass  Poison  60      62       63       80
2  3                   Venusaur  Grass  Poison  80      82       83      100
3  3      VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4                 Charmander   Fire     NaN  39      52       43       60
5  5                 Charmeleon   Fire     NaN  58      64       58       80
6  6                  Charizard   Fire  Flying  78      84       78      109
7  6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130
8  6  CharizardMega Charizard Y   Fire  Flying  78     104       78      159

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False
5       65     80           1      False
6       85    100           1      False
7       85    100           1      False
8      115    100           1      False

In [13]:
print(df.iloc[0,1])

Bulbasaur

In [19]:
for index,row in df.iterrows():
    print(index,row[1:5])
    if index==6:
        break

0 Name      Bulbasaur
Type 1        Grass
Type 2       Poison
HP               45
Name: 0, dtype: object
1 Name      Ivysaur
Type 1      Grass
Type 2     Poison
HP             60
Name: 1, dtype: object
2 Name      Venusaur
Type 1       Grass
Type 2      Poison
HP              80
Name: 2, dtype: object
3 Name      VenusaurMega Venusaur
Type 1                    Grass
Type 2                   Poison
HP                           80
Name: 3, dtype: object
4 Name      Charmander
Type 1          Fire
Type 2           NaN
HP                39
Name: 4, dtype: object
5 Name      Charmeleon
Type 1          Fire
Type 2           NaN
HP                58
Name: 5, dtype: object
6 Name      Charizard
Type 1         Fire
Type 2       Flying
HP               78
Name: 6, dtype: object

In [23]:
df.loc[df['Type 1']=="Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [25]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [30]:
df.sort_values('Type 1', ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
371,339,Barboach,Water,Ground,50,48,43,46,41,60,3,False
97,90,Shellder,Water,NaN,30,65,100,45,25,40,1,False
240,222,Corsola,Water,Rock,55,55,85,65,85,35,2,False
403,368,Gorebyss,Water,NaN,55,84,105,114,75,52,3,False
93,86,Seel,Water,NaN,65,45,55,45,70,45,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
54,49,Venomoth,Bug,Poison,70,65,60,90,75,90,1,False
208,193,Yanma,Bug,Flying,65,65,45,75,45,95,2,False
182,168,Ariados,Bug,Poison,70,90,70,60,60,40,2,False
734,666,Vivillon,Bug,Flying,80,52,50,90,50,89,6,False
179,165,Ledyba,Bug,Flying,40,20,30,40,80,55,2,False

In [31]:
df.sort_values(['#','Attack'],ascending=[0,1])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
...,...,...,...,...,...,...,...,...,...,...,...,...
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False

In [38]:
df['t_stat']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']

In [39]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  t_stat
0         65       65     45           1      False     318
1         80       80     60           1      False     405
2        100      100     80           1      False     525
3        122      120     80           1      False     625
4         60       50     65           1      False     309
..       ...      ...    ...         ...        ...     ...
795      100      150     50           6       True     600
796      160      110    110           6       True     700
797      150      130     70           6       True     600
798      170      130     80           6       True     680
799      130       90     70           6       True     600

[800 rows x 13 columns]

In [37]:
45+49+49+65+65+45

318

In [42]:
df['t_stat2']=df.iloc[:,4:10].sum(axis=1)

In [43]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  t_stat  t_stat2
0         65       65     45           1      False     318      318
1         80       80     60           1      False     405      405
2        100      100     80           1      False     525      525
3        122      120     80           1      False     625      625
4         60       50     65           1      False     309      309
..       ...      ...    ...         ...        ...     ...      ...
795      100      150     50           6       True     600      600
796      160      110    110           6       True     700      700
797      150      130     70           6       True     600      600
798      170      130     80           6       True     680      680
799      130       90     70           6       True     600      600

[800 rows x 14 columns]

In [44]:
df=df.drop(columns='t_stat2')
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  t_stat
0         65       65     45           1      False     318
1         80       80     60           1      False     405
2        100      100     80           1      False     525
3        122      120     80           1      False     625
4         60       50     65           1      False     309
..       ...      ...    ...         ...        ...     ...
795      100      150     50           6       True     600
796      160      110    110           6       True     700
797      150      130     70           6       True     600
798      170      130     80           6       True     680
799      130       90     70           6       True     600

[800 rows x 13 columns]

In [46]:
col_list=list(df.columns)
print(col_list)

['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 't_stat']

In [47]:
df=df[col_list[0:10]+[col_list[-1]]+col_list[10:12]]

In [48]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  t_stat  Generation  Legendary
0         65       65     45     318           1      False
1         80       80     60     405           1      False
2        100      100     80     525           1      False
3        122      120     80     625           1      False
4         60       50     65     309           1      False
..       ...      ...    ...     ...         ...        ...
795      100      150     50     600           6       True
796      160      110    110     700           6       True
797      150      130     70     600           6       True
798      170      130     80     680           6       True
799      130       90     70     600           6       True

[800 rows x 13 columns]

In [52]:
df.to_csv('new_poke.txt',index=False,sep='\t')

In [54]:
df.to_csv('new_poke.csv',index=False)

In [61]:
new_df=df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison') & (df['Sp. Def']>50)]

In [64]:
new_df.to_csv('poke_part.csv')

In [63]:
print(new_df)

       #                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1              Bulbasaur  Grass  Poison   45      49       49       65
1      2                Ivysaur  Grass  Poison   60      62       63       80
2      3               Venusaur  Grass  Poison   80      82       83      100
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122
48    43                 Oddish  Grass  Poison   45      50       55       75
49    44                  Gloom  Grass  Poison   60      65       70       85
50    45              Vileplume  Grass  Poison   75      80       85      110
77    71             Victreebel  Grass  Poison   80     105       65      100
344  315                Roselia  Grass  Poison   50      60       45      100
451  406                  Budew  Grass  Poison   40      30       35       50
452  407               Roserade  Grass  Poison   60      70       65      125
651  590                Foongus  Grass  Poison   69      55       45       55
652  591              Amoonguss  Grass  Poison  114      85       70       85

     Sp. Def  Speed  t_stat  Generation  Legendary
0         65     45     318           1      False
1         80     60     405           1      False
2        100     80     525           1      False
3        120     80     625           1      False
48        65     30     320           1      False
49        75     40     395           1      False
50        90     50     490           1      False
77        70     70     490           1      False
344       80     65     400           3      False
451       70     55     280           4      False
452      105     90     515           4      False
651       55     15     294           5      False
652       80     30     464           5      False

In [68]:
new_df.reset_index(drop=True, inplace=True)

In [74]:
new_df.loc[(new_df['Generation']>=0)]

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, t_stat, Generation, Legendary]
Index: []

In [75]:
df.loc[~(df['Name'].str.contains('Mega'))]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,t_stat,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,405,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,600,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,600,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,600,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,680,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,600,6,True

In [81]:
df.loc[df['Name'].str.contains('pi[a-z]*',regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,t_stat,Generation,Legendary
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,195,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,299,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,390,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,500,1,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,250,2,False
189,175,Togepi,Fairy,NaN,35,20,65,40,65,20,245,2,False
202,187,Hoppip,Grass,Flying,35,35,40,35,55,50,250,2,False
266,247,Pupitar,Rock,Ground,70,84,70,65,70,51,410,2,False
345,316,Gulpin,Poison,NaN,70,43,53,43,53,40,302,3,False
357,326,Grumpig,Psychic,NaN,80,45,65,90,110,80,470,3,False
358,327,Spinda,Normal,NaN,60,60,60,60,60,60,360,3,False
359,328,Trapinch,Ground,NaN,45,100,45,45,45,10,290,3,False
390,357,Tropius,Grass,Flying,99,68,83,72,87,51,460,3,False
463,416,Vespiquen,Bug,Flying,70,80,102,80,102,40,474,4,False
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,220,4,False
490,442,Spiritomb,Ghost,Dark,50,92,108,92,108,35,485,4,False
501,451,Skorupi,Poison,Bug,40,50,90,30,55,65,330,4,False
502,452,Drapion,Poison,Dark,70,90,110,60,75,95,500,4,False
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,308,5,False
596,536,Palpitoad,Water,Ground,75,65,55,65,55,69,384,5,False
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,313,6,False

In [86]:
df.loc[df['Type 1']=='Flame','Type 1']='Grass'

In [87]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  t_stat  Generation  Legendary
0         65       65     45     318           1      False
1         80       80     60     405           1      False
2        100      100     80     525           1      False
3        122      120     80     625           1      False
4         60       50     65     309           1      False
..       ...      ...    ...     ...         ...        ...
795      100      150     50     600           6       True
796      160      110    110     700           6       True
797      150      130     70     600           6       True
798      170      130     80     680           6       True
799      130       90     70     600           6       True

[800 rows x 13 columns]

In [89]:
df.loc[df['Sp. Atk']>100,'Legendary']=True

In [90]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  t_stat  Generation  Legendary
0         65       65     45     318           1      False
1         80       80     60     405           1      False
2        100      100     80     525           1      False
3        122      120     80     625           1       True
4         60       50     65     309           1      False
..       ...      ...    ...     ...         ...        ...
795      100      150     50     600           6       True
796      160      110    110     700           6       True
797      150      130     70     600           6       True
798      170      130     80     680           6       True
799      130       90     70     600           6       True

[800 rows x 13 columns]

In [91]:
df=pd.read_csv('new_poke.csv')

In [94]:
print(df['Legendary'][796])

True

In [97]:
df.loc[df['Sp. Atk']>100, ['Legendary','Generation']]=['test1','test2']

In [98]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  t_stat Generation Legendary
0         65       65     45     318          1     False
1         80       80     60     405          1     False
2        100      100     80     525          1     False
3        122      120     80     625      test2     test1
4         60       50     65     309          1     False
..       ...      ...    ...     ...        ...       ...
795      100      150     50     600          6      True
796      160      110    110     700      test2     test1
797      150      130     70     600      test2     test1
798      170      130     80     680      test2     test1
799      130       90     70     600      test2     test1

[800 rows x 13 columns]

In [99]:
df=pd.read_csv('new_poke.csv')

In [100]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  t_stat  Generation  Legendary
0         65       65     45     318           1      False
1         80       80     60     405           1      False
2        100      100     80     525           1      False
3        122      120     80     625           1      False
4         60       50     65     309           1      False
..       ...      ...    ...     ...         ...        ...
795      100      150     50     600           6       True
796      160      110    110     700           6       True
797      150      130     70     600           6       True
798      170      130     80     680           6       True
799      130       90     70     600           6       True

[800 rows x 13 columns]

In [119]:
df.groupby(['Type 1']).sum().sort_values('Attack',ascending=False)

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,t_stat,Generation,Legendary
Type 1,,,,,,,,,,,,
Water,33946,SquirtleWartortleBlastoiseBlastoiseMega Blasto...,FightingPoisonPoisonPsychicPsychicPsychicIceIc...,8071,8305,8170,8379,7898,7388,48211,320,4
Normal,31279,PidgeyPidgeottoPidgeotPidgeotMega PidgeotRatta...,FlyingFlyingFlyingFlyingFlyingFlyingFairyFairy...,7573,7200,5865,5470,6245,7012,39365,299,2
Grass,24141,BulbasaurIvysaurVenusaurVenusaurMega VenusaurO...,PoisonPoisonPoisonPoisonPoisonPoisonPoisonPois...,4709,5125,4956,5425,4930,4335,29480,235,3
Bug,23080,CaterpieMetapodButterfreeWeedleKakunaBeedrillB...,FlyingPoisonPoisonPoisonPoisonGrassGrassPoison...,3925,4897,4880,3717,4471,4256,26146,222,0
Fire,17025,CharmanderCharmeleonCharizardCharizardMega Cha...,FlyingDragonFlyingFlyingRockFlyingFightingFigh...,3635,4408,3524,4627,3755,3871,23820,167,5
Rock,17280,GeodudeGravelerGolemOnixOmanyteOmastarKabutoKa...,GroundGroundGroundGroundWaterWaterWaterWaterFl...,2876,4086,4435,2787,3321,2460,19965,152,4
Psychic,21706,AbraKadabraAlakazamAlakazamMega AlakazamDrowze...,FairyFightingFlyingFlyingFlyingGrassFairyFairy...,4026,4073,3858,5609,4918,4645,27129,193,14
Dragon,15180,DratiniDragonairDragoniteAltariaAltariaMega Al...,FlyingFlyingFairyFlyingFlyingPsychicPsychicPsy...,2666,3588,2764,3099,2843,2657,17617,124,12
Ground,11401,SandshrewSandslashDiglettDugtrioCuboneMarowakR...,RockRockFlyingDragonDragonPsychicPsychicFireRo...,2361,3064,2715,1807,2008,2045,14000,101,4
Electric,15994,PikachuRaichuMagnemiteMagnetonVoltorbElectrode...,SteelSteelFlyingDragonSteelGhostFireWaterIceFl...,2631,3040,2917,3961,3243,3718,19510,144,4
Dark,14302,UmbreonMurkrowSneaselHoundourHoundoomHoundoomM...,FlyingIceFireFireFireGhostGhostFlyingIceFighti...,2071,2740,2177,2314,2155,2361,13818,125,2
Fighting,9824,MankeyPrimeapeMachopMachokeMachampHitmonleeHit...,PsychicPsychicPsychicSteelSteelDarkFlying,1886,2613,1780,1434,1747,1784,11244,91,0
Steel,11957,SteelixSteelixMega SteelixSkarmoryMawileMawile...,GroundGroundFlyingFairyFairyRockRockRockPsychi...,1761,2503,3412,1823,2177,1492,13168,104,4
Ghost,15568,GastlyHaunterGengarGengarMega GengarMisdreavus...,PoisonPoisonPoisonPoisonFlyingFlyingDarkDragon...,2062,2361,2598,2539,2447,2059,14066,134,2
Poison,7050,EkansArbokNidoran (Female)NidorinaNidoqueenNid...,GroundGroundFlyingFlyingFlyingDarkDarkBugDarkF...,1883,2091,1927,1692,1803,1780,11176,71,0
Ice,10165,JynxArticunoSwinubPiloswineDelibirdSmoochumSno...,PsychicFlyingGroundGroundFlyingPsychicWaterWat...,1728,1746,1714,1861,1831,1523,10403,85,2
Fairy,7642,ClefairyClefableCleffaTogepiTogeticSnubbullGra...,FlyingFlying,1260,1046,1117,1335,1440,826,7024,70,1
Flying,2711,TornadusIncarnate FormeTornadusTherian FormeNo...,DragonDragon,283,315,265,377,290,410,1940,22,2

In [126]:
df['count']=1

In [128]:
df.groupby(['Type 1','Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64